# Generated by Django 5.0.4 on 2024-06-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='img',
            new_name='photo',
        ),
    ]
