# Generated by Django 5.0.4 on 2024-06-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_question_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
