# Generated by Django 5.0.4 on 2024-06-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tweet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
